### ISSUE TITLE
Add appliance ha-nodes endpoint to sdk

### ISSUE THREAD

**Issue by trir262** [HewlettPackard/oneview-python#157]
Hello,
I really like this oneview package! I noticed the rest api reference has documentation about getting the appliance ha nodes information (via `/rest/appliance/ha-nodes`). This shows quite some information about appliances ha mode, which is useful in our scenario.
I am talking about [ha-nodes](https://techlibrary.hpe.com/docs/enterprise/servers/oneview5.0/cicf-api/en/index.html#rest/appliance/ha-nodes).
Can I submit a PR containing this info?
Regards,

**Comment by nabhajit-ray** [comment]
Hi Trir262,

We appreciate contribution  to our SDK. Please raise the PR and we will review it.Thanks

**Comment by VenkateshRavula** [comment]
Hi @trir262, Thanks for your contribution by raising this PR. But unfortunately this PR failed to pass the build validation tests because of some permission denied error.
Moreover the file which you tried to modify needs to be refactored before adding new changes. Also you have merged endpoints of different resources into single library file which is not accepted by our SDK team.
So we will be picking this as an enhancement request and make the necessary modifications to the library file to satisfy your requirement and will raise a different PR from our side.
Soon we will get back to you with our fix.

**Comment by VenkateshRavula** [comment]
Hi @trir262, the fix is merged to master and hence I am closing this issue.
