### ISSUE TITLE
Oneview WebServer server truncating responses . on REST Calls?

### ISSUE THREAD

**Issue by zeshan1977** [HewlettPackard/oneview-python#166]
Please see below code
Isssue: The serverhardware object has around 202 members
Yet only a MAX of 32 are returnin. Is there a  setting we have to turn on OneView and/or Global Dashboard
VERSION API: LATEST
OV Installation latest
<PRE>
get_server_hardware_url = f'https://{ov_ip}/rest/server-hardware
 headers = {
        'X-Api-Version': '1200',
        'Content-Type': 'application/json',
        'Auth': sessionID
 }
 res = requests.get(get_server_hardware_url, headers = headers, verify=False)
 print(">>Response ")
 print(res['total'])#-->: 202,
 print(res['start'])#-->: 0,
 print(res['count'])#-->: 32,
 print(res['type'])#-->: 'server-hardware-list-10',
**# How can we tell the webserver, with a custom tag to make below:count= {'total'}**
 print(res['uri'])#-->: '/rest/server-hardware?start=0&count=32'}
</PRE>

**Comment by yuvirani** [comment]
Hi @zeshan1977, We are looking into this issue, will update you with the fix soon.

**Comment by yuvirani** [comment]
@zeshan1977,
I understand that you would like to get all 202 members  in a single page as GET response. But as you can see, each member has a lot of attributes which leads to pagination. Since the members are more, you must provide the uri with count. Please note "nextPageUri" is not null for pagination.

Uri: '/rest/server-hardware?start=0&count=202'

You can also use the method "get_all" implemented in our SDK which returns all the members.
https://github.com/HewlettPackard/oneview-python/blob/master/examples/server_hardware.py

Please let us know if this solves your issue.

**Comment by yuvirani** [comment]
Please modify the url and keep the header as it is:

get_server_hardware_url = f'https://{ov_ip}/rest/server-hardware?start=0&count=202

**Comment by zeshan1977** [comment]
Thank you.
